---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivebox
spec:
  selector:
    matchLabels:
      app: archivebox
  replicas: 1
  template:
    metadata:
      labels:
        app: archivebox
    spec:
      initContainers:
        - name: init-archivebox
          image: ghcr.io/archivebox/archivebox:0.8.5rc51
          args: ['init']
          workingDir: /data/data
          volumeMounts:
            - mountPath: /data
              name: archivebox-volume
          env:
            - name: ADMIN_USERNAME
              value: admin
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: archivebox
                  key: ADMIN_PASSWORD
            - name: PUID
              value: '911'
            - name: PGID
              value: '911'
            - name: DATA_DIR
              value: /data/data

      containers:
        - name: archivebox
          args: ['server']
          workingDir: /data/data
          image: ghcr.io/archivebox/archivebox:0.8.5rc51
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          env:
            - name: PUID
              value: '911'
            - name: PGID
              value: '911'
            - name: DATA_DIR
              value: /data/data
            - name: USER_AGENT
              value: "\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36\""
          volumeMounts:
            - mountPath: /data
              name: archivebox-volume
            - mountPath: /data/data/archive
              name: archivebox-data-volume
      restartPolicy: Always
      volumes:
        - name: archivebox-volume
          persistentVolumeClaim:
            claimName: archivebox-pvc
        - name: archivebox-data-volume
          persistentVolumeClaim:
            claimName: archivebox-data-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: archivebox-remove-chrome-data
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - image: busybox:1.36.1
              name: archivebox-remove-chrome-data
              command: ["sh", "-c", "rm -rf /data/data/personas/Default/chrome_profile"]
              volumeMounts:
                - mountPath: /data
                  name: archivebox-volume
          volumes:
            - name: archivebox-volume
              persistentVolumeClaim:
                claimName: archivebox-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: archivebox
  name: archivebox-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: archivebox
  name: archivebox-data-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: archivebox-service
spec:
  selector:
    app: archivebox
  ports:
    - name: http
      port: 8000
  externalIPs:
    - 172.16.1.10
