kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
- kind: ServiceAccount
  name: deployment-restart
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: misskey-develop-deployment-restart
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: deployment-restart
          restartPolicy: Never
          containers:
            - image: bitnami/kubectl:1.33.2
              name: deployment-restart
              command: ["kubectl", "rollout", "restart", "deployment", "misskey-develop-misskey-deployment"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: update-deployment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: update-deployment
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: redeploy
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: update-deployment
          restartPolicy: Never
          containers:
            - image: ghcr.io/steve-0628/deployment:latest
              imagePullPolicy: Always
              name: renew-deployment
              command: ["kubectl", "apply", "-f", "/deployment"]
