apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio-deployment
spec:
  selector:
    matchLabels:
      app: factorio
  replicas: 1
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
        - name: factorio
          image: factoriotools/factorio:stable
          ports:
            - containerPort: 34197
          volumeMounts:
            - name: factorio-volume
              mountPath: /factorio/saves
          env:
            - name: DLC_SPACE_AGE
              value: "false"
      volumes:
        - name: factorio-volume
          persistentVolumeClaim:
            claimName: factorio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-service
spec:
  selector:
    app: factorio
  ports:
    - protocol: UDP
      port: 34197
  externalIPs:
    - 172.16.1.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5G
