apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filebrowser-statefulset
spec:
  selector:
    matchLabels:
      app: filebrowser-app
  replicas: 1
  template:
    metadata:
      labels:
        app: filebrowser-app
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:v2.60.0@sha256:a7b81cab28cf93de4c3ac97403d92f38d23191d7247e9c37611d4afa2d8d0c69
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: filebrowser-nfs
              mountPath: /srv
            - name: filebrowser-db
              mountPath: /database
            - name: filebrowser-config
              mountPath: /config/settings.json
              subPath: settings.json
      volumes:
        - name: filebrowser-nfs
          nfs:
            server: 172.16.1.3
            path: /mnt/data-tank/share
        - name: filebrowser-db
          persistentVolumeClaim: 
            claimName: filebrowser-db-pvc
        - name: filebrowser-config
          configMap:
            name: filebrowser-configmap
            items:
              - key: settings.json
                path: settings.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-configmap
data:
  settings.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-db-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: filebrowser-app

