apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed-deployment
spec:
  selector:
    matchLabels:
      app: librespeed
  replicas: 1
  template:
    metadata:
      labels:
        app: librespeed
    spec:
      containers:
        - name: librespeed
          image: linuxserver/librespeed:5.4.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: librespeed-service
spec:
  selector:
    app: librespeed
  ports:
    - protocol: TCP
      port: 80
