apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless-lb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mariadb
    type: LoadBalancer
    loadBalancerIP: 172.16.5.17
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-statefulset
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.8.5-ubi9@sha256:b53f2fd9615cd21f004e59fdabd5a1cadb19c74fcf376a14b35e6767d3382ecf
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: super_secret_mariadb_password
        - name: MARIADB_USER
          value: epgstation
        - name: MARIADB_PASSWORD
          value: epgstation
        - name: MARIADB_DATABASE
          value: epgstation
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
