apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mysql
  selector:
    app: mariadb
  type: LoadBalancer
  loadBalancerIP: 172.16.5.17
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-statefulset
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11.8.9-ubi9@sha256:deb8c8a2e960b45ec7bedd68e9de88bbb32687d2027327b1e2c4f8f2341e8827
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: super_secret_mariadb_password
        - name: MARIADB_USER
          value: epgstation
        - name: MARIADB_PASSWORD
          value: epgstation
        - name: MARIADB_DATABASE
          value: epgstation
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
