apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mikopbx
spec:
  selector:
    matchLabels:
      app: mikopbx
  replicas: 1
  template:
    metadata:
      labels:
        app: mikopbx
    spec:
      containers:
        - name: mikopbx
          image: ghcr.io/mikopbx/mikopbx-x86-64:2024.1.114
          command: ["/sbin/init.sh"]
          # command:
          #   - sleep
          #   - "3600"
          lifecycle:
            postStart:
              exec:
                command: ["/sbin/fixperm.sh"]
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 300
            initialDelaySeconds: 60
            periodSeconds: 10
          ports:
            - containerPort: 8080
          env:
            - name: WEB_PORT
              value: "8080"
          volumeMounts:
            - name: mikopbx-cf-volume
              mountPath: /cf
            - name: mikopbx-config-volume
              mountPath: /config
            - name: resolve
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
            - name: init
              mountPath: /sbin/init.sh
              subPath: init.sh
            - name: fixperm
              mountPath: /sbin/fixperm.sh
              subPath: fixperm.sh
      volumes:
        - name: mikopbx-cf-volume
          persistentVolumeClaim:
            claimName: mikopbx-cf-pvc
        - name: mikopbx-config-volume
          persistentVolumeClaim:
            claimName: mikopbx-config-pvc
        - name: resolve
          configMap:
            name: mikopbx-patch
            items:
              - key: resolv.conf
                path: resolv.conf
        - name: init
          configMap:
            name: mikopbx-patch
            items:
              - key: init.sh
                path: init.sh
                mode: 0755
        - name: fixperm
          configMap:
            name: mikopbx-patch
            items:
              - key: fixperm.sh
                path: fixperm.sh
                mode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mikopbx-patch
data:
  resolv.conf: |
    search default.svc.cluster.local svc.cluster.local cluster.local 172.16.0.1 1.1.1.1
    nameserver 10.96.0.10
    options ndots:5
  init.sh: |
    #!/bin/sh
    ln -s /dev/stdout /dev/console
    exec /sbin/docker-entrypoint
  fixperm.sh: |
    #!/bin/sh
    mkdir -p /cf/conf
    chmod 777 /cf/conf
    while [ ! -e /cf/conf/mikopbx.db ]; do
      sleep 0.1
    done
    sleep 1
    chmod 666 /cf/conf/mikopbx.db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mikopbx-cf-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mikopbx-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mikopbx-service-lb
spec:
  selector:
    app:  mikopbx
  ports:
    - port: 5060
      protocol: UDP
      name: sipudp
    - port: 5060
      protocol: TCP
      name: siptcp
    - port: 8080
      name: webui
    - port: 10000
      protocol: UDP
      name: port0
    - port: 10001
      protocol: UDP
      name: port1
    - port: 10002
      protocol: UDP
      name: port2
    - port: 10003
      protocol: UDP
      name: port3
    - port: 10004
      protocol: UDP
      name: port4
    - port: 10005
      protocol: UDP
      name: port5
    - port: 10006
      protocol: UDP
      name: port6
    - port: 10007
      protocol: UDP
      name: port7
    - port: 10008
      protocol: UDP
      name: port8
    - port: 10009
      protocol: UDP
      name: port9
    - port: 10010
      protocol: UDP
      name: port10
  loadBalancerIP: 172.16.10.200
  type: LoadBalancer
  externalTrafficPolicy: Local
