---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    CLOUDFLARE_TUNNEL_TOKEN: AgBgbmC79hBEwOs99jFZRZ/D19XXKOoYQJwYVFxSUlZCoJi/V84jGB/Yj/pUs85WFmyg2xEaORCD4Ie1h23kxZ495kREb42fKj4gMkW0YFsN3sq6TMITVq0wWLrhAPt9BoZedXzzw6SzMjy0gSKdlr78mk2q3MP+I5zf9e1JPlv94BmTewRNmJfHzCYJW41l06DbMkg6OjkS3rxqxWO53YExPFGE2YYrIbXjrJABRUcuib3FEOEqWrCZMTXvEt4zRYG1O7Q34VsIDBN9C6JE3A+8BrO+jEvoivAqbnI45Iie0d643lBZQMK1LGDA0MescEG4GjMYwvdQokGXdJeS3Quju3PWSEGaA7FGInIXPcyVbUvE0ewODZM0YDA3sZEfT/Epu3gLzV/Qdd/KVsOvA4887aCshK+8YXcwlurotNxGy+M3FoCTgBX5oshE9rPxTrmhHq+ik/8uSp2CjnOqZzJxv6DjUvPfrYdoY54DANo1KbGzpO34x9Ez+qesOYSJeIbIHWt9LDtTZ1xboU7Y8H3EzRqbiVL3yYR+du9b0214Avtl5t+xgZDom9ft/KyTx7+k5p9oFtB6X2xO2ajTyZqqpbMnV9U8v1a1EYLxbAtCMyDBcyrut0YPQ+Bjq3MnI8uLK/hkfIXJj8swtLlV8QlUcUWmHmDLTZWzRC9+8x4i7Usz4Fd2m5e21mdT3CS2lhpv1TugR93Hevq/u4SzMf2pqyrTKRGGY0uGH+x7FB4NW9j76axS1PGYiO99PT4QTfkmzOnInDDas1r0zRvshRQa8WfvWV5EIsG2LruluV6p0Nulxr724iphPVsQvDe/IfvlWWD7YDDjf4Gf4wJPvWVpvTrDrWzwq1HjImpQ16OMddo91gcL6kKLz6H8lJcwAAA9R4aniD1t8DDN3NYegzgR1UR2wOfKMbFlO+61OpFAzEtqo52HkDlceg==
  template:
    metadata:
      name: cloudflared
      namespace: default
    type: Opaque
