---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBBz10SCKAnw959gKgfJ1hfCemSZQF92QVfg5Gk+UUAb7ynsH6vDidB2GB7MeReqiW4etbP3MGZPyf+py1Nx4hflpcJp9mkYR1nEwZy0GV37RMelmAA/vbuEPgEd8D1+YKwq3jNG0uBQJO3+AoZ6h5MLssqoToUOZJm7NUHMt756a9BPy+Wm6pF/w06DoH05Tl3iWrppmHpM8raBCk01scgrNKoyur7HdPyVIIWy9WSFqPdltgWwAOwGGjKgik3w6m/JClV65/R6oQEFBrlLxBfvWlVVazytQwXBKz3vPR3i2lWwqVHdJaU+mwTkPJ/12ORWHHpwIctoUAYnXdjUtwUUX07tjJFopxtflQyDkkdBr945R/46ngq4a2uz/JGT0twP6squMspeL4LOUxwlWiKhWIhwloxvOJ3/7uDDKqAtxnYyvyy2M8ekThR3w7Jzz0n19J88A/RR/OtxheR0EB45UOCTXfDrWS0qqQqqf2JNI71lAbR6alMCcC9sgkKcH0PZ3eSyKiisSAg05ucUH8wHMSogIA8EnjQRDjC1p8P8BTHAL1Kj7ABLJqwTLHvDiHfxzjIhfOelkAuK1Ffz/KuQl9Qa5DIkAwBxMibqHJpaFq2S6RpU0vCETSdI5Cp+Rn6cZzJVE/7rkA2xCpdoTb+SG3o5/k5XIyuwjD5BismpqMN2mLK0tIOckyybp5xu/OvQaSqcbzZAUU33anSROYClMVX0acosji3gET4JYtUAHG58b+8lLFrneH0C60738Q3DKBvkUTc/EHIm4z7yYvdtTSsfKcg2C0mkOp1kCKiF7DXy1rivtkKtiSlcgzhB/Ec1BKSWJdkTy2K
  template:
    metadata:
      name: ghcr
      namespace: default
    type: kubernetes.io/dockerconfigjson
