name: Push to GHCR

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: lowercase
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/${{ steps.lowercase.outputs.lowercase }}:latest
